### ISSUE TITLE
scala 2.12 support

### ISSUE THREAD

**Issue by aappddeevv** [lucidsoftware/xtract#2]
Upgrade build to support 2.11 and 2.12.

**Comment by tmccombs** [comment]
I started working on this on https://github.com/lucidsoftware/xtract/tree/2-12. But I can't get it to compile the tests on 2.12 because  `"org.specs2" % "specs2-cats_2.12" % "3.8.9"` doesn't exist. More generally, there doesn't seem to be an artifact for specs2-cats on 2.12 (which is a dependency of specs2, which is used for the unit tests).

Also, play_functional for 2.12 is still just a release candidate. It isn't stable yet. If you want make a pull request with working support for 2.12, I'll merge it. But for now, I'm inclined to wait until upstream dependencies have better support for 2.12.

**Comment by pauldraper** [comment]
The first problem can probably be solved by depending on `specs2-core` instead of `specs2`.

**Comment by tmccombs** [comment]
The second problem could be resolved by #5

**Comment by tmccombs** [comment]
I've released a 2.12 build. It should show up on maven central soon.
